# Generated by Django 6.0 on 2025-12-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniqueitems',
            name='current_stock',
        ),
    ]
