# Generated by Django 6.0 on 2025-12-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_uniqueitems_current_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniqueItems',
            new_name='UniqueItem',
        ),
    ]
