# Generated by Django 6.0 on 2025-12-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_uniqueitems_uniqueitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueitem',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
