# Generated by Django 6.0 on 2025-12-18 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=10)),
                ('status', models.CharField(default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField()),
                ('sales', models.FloatField(default=0)),
                ('dayofweek', models.IntegerField(default=0)),
                ('publicholiday', models.BooleanField(default=0)),
                ('schoolholiday', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StocktakeItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('counted', models.IntegerField(default=0)),
                ('usage', models.IntegerField(default=0)),
                ('endstock', models.IntegerField(default=0)),
                ('stocktake', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stocktake.stocktakes')),
            ],
        ),
    ]
