# Generated by Django 6.0 on 2025-12-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stocktakes',
            new_name='Stocktake',
        ),
        migrations.RenameModel(
            old_name='StocktakeItems',
            new_name='StocktakeItem',
        ),
    ]
