# Generated by Django 6.0 on 2025-12-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0002_rename_stocktakes_stocktake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
