# Generated by Django 6.0 on 2025-12-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0003_stocktake_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktake',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
