# Generated by Django 6.0 on 2025-12-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0004_alter_stocktake_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktakeitem',
            name='counted',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
