# Generated by Django 6.0 on 2025-12-22 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0005_alter_stocktakeitem_counted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktake',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 12, 22, 6, 7, 24, 93128, tzinfo=datetime.timezone.utc)),
        ),
    ]
