# Generated by Django 6.0 on 2025-12-22 06:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_uniqueitem_stock'),
        ('stocktake', '0006_alter_stocktake_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakeitem',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.uniqueitem'),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 12, 22, 6, 26, 4, 484507, tzinfo=datetime.timezone.utc)),
        ),
    ]
