# Generated by Django 6.0 on 2025-12-22 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0007_stocktakeitem_item_alter_stocktake_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktake',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 12, 22, 6, 28, 58, 796765, tzinfo=datetime.timezone.utc)),
        ),
    ]
