# Generated by Django 6.0 on 2025-12-22 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0008_alter_stocktake_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktakeitem',
            name='endstock',
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 12, 22, 6, 41, 31, 796695, tzinfo=datetime.timezone.utc)),
        ),
    ]
