# Generated by Django 6.0 on 2025-12-22 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0009_remove_stocktakeitem_endstock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktake',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 12, 22, 6, 58, 18, 744586, tzinfo=datetime.timezone.utc)),
        ),
    ]
