# Generated by Django 6.0 on 2025-12-24 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0010_alter_stocktake_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktake',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 12, 24, 5, 48, 14, 735109, tzinfo=datetime.timezone.utc)),
        ),
    ]
