# Generated by Django 6.0 on 2026-01-07 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0014_alter_stocktake_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktake',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 1, 7, 8, 56, 41, 600929, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='counted',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
